name: Run Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker
        run: docker run IMAGE_NAME:TAG
