name: Docker Image CI

on:
  push:
    branches: [ "5.x" ]
  pull_request:
    branches: [ "5.x" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 运行docker映像
      run: docker run -d -p 8080:80 --shm-size=1gb --name=weserv ghcr.io/weserv/images:5.x
